"""update table models

Revision ID: 7b70da09ae6a
Revises: 7d3fd8ea6929
Create Date: 2026-02-17 22:42:55.086484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b70da09ae6a'
down_revision: Union[str, Sequence[str], None] = '7d3fd8ea6929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('majors_major_name_key'), 'majors', type_='foreignkey')
    op.drop_column('majors', 'institute_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('majors', sa.Column('institute_id', sa.INTEGER(), nullable=True))
    op.execute("UPDATE majors SET institute_id = 1")
    # делаем NOT NULL
    op.alter_column('majors', 'institute_id', nullable=False)
    op.create_foreign_key(op.f('majors_major_name_key'), 'majors', 'institutes', ['institute_id'], ['id'])
    # ### end Alembic commands ###
