"""add institute model

Revision ID: 7d3fd8ea6929
Revises: 4fd595d535e9
Create Date: 2026-02-17 18:10:19.265026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d3fd8ea6929'
down_revision: Union[str, Sequence[str], None] = '4fd595d535e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institute_name', sa.String(), nullable=False),
    sa.Column('major_id', sa.Integer(), nullable=False),
    sa.Column('count_students', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['major_id'], ['majors.id']),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institute_name')
    )

    op.drop_column('majors', 'major_description')

    # Создаем дефолтный институт, если таблица пустая
    op.execute("""
        INSERT INTO institutes (institute_name, major_id, count_students)
        SELECT 'Default Institute', id, 0
        FROM majors
        WHERE NOT EXISTS (SELECT 1 FROM institutes)
        LIMIT 1
        """)
    op.add_column('majors', sa.Column('institute_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'majors', 'institutes', ['institute_id'], ['id'])

    op.add_column('students', sa.Column('institute_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'students', 'institutes', ['institute_id'], ['id'])

    # Заполняем поле institute_id любым значением
    op.execute("""
        UPDATE majors
        SET institute_id = (SELECT id FROM institutes LIMIT 1)
        WHERE institute_id IS NULL
        """)

    op.execute("""
        UPDATE students
        SET institute_id = (SELECT id FROM institutes LIMIT 1)
        WHERE institute_id IS NULL
        """)

    # Возвращаем значения NOT NULL
    op.alter_column("majors", "institute_id", nullable=False)
    op.alter_column("students", "institute_id", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("students_institute_id_fkey", 'students', type_='foreignkey')
    op.drop_column('students', 'institute_id')
    op.drop_constraint("majors_institute_id_fkey", 'majors', type_='foreignkey')
    op.drop_column('majors', 'institute_id')
    op.drop_table('institutes')
    op.add_column('majors', sa.Column('major_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
